# Generated by Django 5.1.6 on 2025-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.CharField(max_length=50),
        ),
    ]
