# Generated by Django 5.1.6 on 2025-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundweb', '0002_alter_track_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(max_length=500),
        ),
    ]
